# Esercitazione

## Istruzioni
Valgono le stesse istruzioni delle esercitazioni precedenti. 

Scrivi il programma Python nella cella sotto il testo dell'esercizio (o creane una nuova). Stampa sempre a video il risultato finale per verificare la correttezza dell'esercizio.  Talvolta richiamiamo alcuni concetti importanti in una cella di codice sotto il testo dell'esercizio, prova a eseguirla ed eventualmente modificarla per assicurarti di aver capito il necessario.


## Consegna
Valgono le regole delle esercitazioni precedenti.

E' obbligatorio **consegnare la soluzione di tutti gli esercizi** (tranne quelli marcati come opzionali) **entro la scadenza**, come specificato nell'apposito assignment su iCorsi.  Per consegnare:
- eseguire l'intero notebook partendo da zero (`Kernel -> Restart & Run All`), e controllare che le soluzioni siano quelle attese;
- esportare il notebook in formato html (`File -> Download as...`) e consegnare il file risultante.

Nel caso non abbiate potuto completare uno o piu' esercizi, descrivete il problema incontrato e **consegnate comunque il file con il resto delle soluzioni**.

## Dataset IMBD

Leggi la documentazione relativa al dataset a [questo link](https://www.kaggle.com/stefanoleone992/imdb-extensive-dataset), e scaricalo.  Se non vuoi creare un account su kaggle, scarica lo zip da [questo link](https://drive.switch.ch/index.php/s/ios1uvNy81xxmyV) sullo switchdrive del docente (non divulgarlo, va usato solo dagli studenti del corso).

In questa esercitazione lavoreremo con il *movies dataset*, ovvero il file `IMDb movies.csv`.

La directory corrente, rispetto alla quale dobbiamo specificare la posizone del file, e' questa:

In [1]:
pwd

'C:\\Users\\Matte\\OneDrive - SUPSI\\A.A. 2022-2023\\Corsi\\SA\\Data Science\\Excercises\\s0'

## Esercizio 0

### 0.0
Importa il dataset con pandas, in un dataframe che chiamermo `df` nel seguito.

In [2]:
import pandas as pd
import numpy as np
df = pd.read_csv("data/IMDb movies.csv")
print("......Head.....")

print(df.head(3))
print("......Tail.....")
print(df.tail(3))
print(".....Sample......")
print(df.sample(3))

......Head.....
  imdb_title_id                        title               original_title  \
0     tt0000009                   Miss Jerry                   Miss Jerry
1     tt0000574  The Story of the Kelly Gang  The Story of the Kelly Gang
2     tt0001892               Den sorte drøm               Den sorte drøm

   year date_published                    genre  duration           country  \
0  1894     1894-10-09                  Romance        45               USA
1  1906     1906-12-26  Biography, Crime, Drama        70         Australia
2  1911     1911-08-19                    Drama        53  Germany, Denmark

  language         director  ...  \
0     None  Alexander Black  ...
1     None     Charles Tait  ...
2      NaN        Urban Gad  ...

                                              actors  \
0  Blanche Bayliss, William Courtenay, Chauncey D...
1  Elizabeth Tait, John Tait, Norman Campbell, Be...
2  Asta Nielsen, Valdemar Psilander, Gunnar Helse...

                                         description avg_vote votes  budget  \
0  The adventures of a female reporter in the 1890s.      5.9   154     NaN
1  True story of notorious Australian outlaw Ned ...      6.1   589  $ 2250
2  Two men of high rank are both wooing the beaut...      5.8   188     NaN

   usa_gross_income worlwide_gross_income metascore reviews_from_users  \
0               NaN                   NaN       NaN                1.0
1               NaN                   NaN       NaN                7.0
2               NaN                   NaN       NaN                5.0

   reviews_from_critics
0                   2.0
1                   7.0
2                   2.0

[3 rows x 22 columns]
......Tail.....
      imdb_title_id                       title              original_title  \
85852     tt9911774   Padmavyuhathile Abhimanyu   Padmavyuhathile Abhimanyu
85853     tt9914286           Sokagin Çocuklari           Sokagin Çocuklari
85854     tt9914942  La vida sense la Sara Amat  La vida sense la Sara Amat

       year date_published          genre  duration country   language  \
85852  2019     2019-03-08          Drama       130   India  Malayalam
85853  2019     2019-03-15  Drama, Family        98  Turkey    Turkish
85854  2019     2020-02-05          Drama        74   Spain    Catalan

                director  ...  \
85852    Vineesh Aaradya  ...
85853  Ahmet Faik Akinci  ...
85854          Laura Jou  ...

                                                  actors  \
85852  Anoop Chandran, Indrans, Sona Nair, Simon Brit...
85853  Ahmet Faik Akinci, Belma Mamati, Metin Keçeci,...
85854  Maria Morera Colomer, Biel Rossell Pelfort, Is...

                                             description avg_vote votes  \
85852                                                NaN      7.9   265
85853                                                NaN      6.4   194
85854  Pep, a 13-year-old boy, is in love with a girl...      6.7   102

       budget  usa_gross_income worlwide_gross_income metascore  \
85852     NaN               NaN                   NaN       NaN
85853     NaN               NaN                $ 2833       NaN
85854     NaN               NaN               $ 59794       NaN

      reviews_from_users  reviews_from_critics
85852                NaN                   NaN
85853                NaN                   NaN
85854                NaN                   2.0

[3 rows x 22 columns]
.....Sample......
      imdb_title_id             title    original_title  year date_published  \
30596     tt0119150              Fred              Fred  1997     1997-03-12
28057     tt0109803  Huo yun chuan qi  Huo yun chuan qi  1994     1994-05-26
71474     tt3497596              Zaba              Zaba  2017           2018

                       genre  duration  \
30596               Thriller        84
28057  Action, Comedy, Drama        90
71474                  Drama        78

                                                 country   language  \
30596                                             France     French
28057                                          Hong Kong  Cantonese
71474  Bosnia and Herzegovina, Republic of North Mace...    Bosnian

             director  ...                                             actors  \
30596  Pierre Jolivet  ...  Vincent Lindon, Clotilde Courau, François Berl...
28057   Woo-Ping Yuen  ...  Brigitte Lin, Siu Chung Mok, Sandra Kwan Yue N...
71474     Elmir Jukic  ...  Emir Hadzihafizbegovic, Aleksandar Seksan, Mir...

                                             description avg_vote votes  \
30596  This is the story of a qualified but unemploye...      6.4   227
28057  When Red Dragon is send out to retrieve a lett...      6.2   188
71474  Zeko, a barber and a former fighter with PTSD,...      7.4   280

       budget  usa_gross_income worlwide_gross_income metascore  \
30596     NaN               NaN                   NaN       NaN
28057     NaN               NaN                   NaN       NaN
71474     NaN               NaN                 $ 991       NaN

      reviews_from_users  reviews_from_critics
30596                2.0                   2.0
28057                6.0                   6.0
71474                NaN                   1.0

[3 rows x 22 columns]

C:\Users\Matte\AppData\Local\Temp\ipykernel_6660\2841420144.py:3: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("data/IMDb movies.csv")

### 0.1
Visualizza le prime 3 righe (`df.head(...)`), le ultime 3 (`df.tail(...)`), e 3 righe a caso (`df.sample(...)`).

Nota: per imporre il massimo di colonne da visualizzare, utilizza il comando `pd.set_option('display.max_columns', N)` dove `N` e' il numero massimo di colonne che vuoi visualizzare.

### 0.2
Stampa il nome delle colonne del dataset.

Facendo anche riferimento alla descrizione del dataset, per ogni colonna descrivi brevemente:
- Il significato della colonna
- Il tipo di dati (stringa? intero?)
- La colonna puo' avere valori nulli? Se si', come sono rappresentati?

In [3]:
columns=df.columns
for e in columns:
    print(f"name: {e} type:{df[e].apply(type).unique()} null:{df.isnull().any()[e]} character: Nan")

name: imdb_title_id type:[<class 'str'>] null:False character: Nan
name: title type:[<class 'str'>] null:False character: Nan
name: original_title type:[<class 'str'>] null:False character: Nan
name: year type:[<class 'int'> <class 'str'>] null:False character: Nan
name: date_published type:[<class 'str'>] null:False character: Nan
name: genre type:[<class 'str'>] null:False character: Nan
name: duration type:[<class 'int'>] null:False character: Nan
name: country type:[<class 'str'> <class 'float'>] null:True character: Nan
name: language type:[<class 'str'> <class 'float'>] null:True character: Nan
name: director type:[<class 'str'> <class 'float'>] null:True character: Nan
name: writer type:[<class 'str'> <class 'float'>] null:True character: Nan
name: production_company type:[<class 'str'> <class 'float'>] null:True character: Nan
name: actors type:[<class 'str'> <class 'float'>] null:True character: Nan
name: description type:[<class 'str'> <class 'float'>] null:True character: Nan
name: avg_vote type:[<class 'float'>] null:False character: Nan
name: votes type:[<class 'int'>] null:False character: Nan
name: budget type:[<class 'float'> <class 'str'>] null:True character: Nan
name: usa_gross_income type:[<class 'float'> <class 'str'>] null:True character: Nan
name: worlwide_gross_income type:[<class 'float'> <class 'str'>] null:True character: Nan
name: metascore type:[<class 'float'>] null:True character: Nan
name: reviews_from_users type:[<class 'float'>] null:True character: Nan
name: reviews_from_critics type:[<class 'float'>] null:True character: Nan

## Esercizio 1 (domande facili)
Scrivi del codice per rispondere alle seguenti domande.

- Qual e' la durata media dei film presenti nel dataset?
- Visualizza il titolo del film piu' lungo, e il titolo del film piu' breve.
- Visualizza il titolo di un film a caso che e' uscito nell'anno in cui sei nato.  Puoi usare il metodo `sample`, visto sopra.
- Qual e' il tuo regista preferito?  Inserisci il suo nome e cognome in una variabile (se vuoi puoi usare la funzione `input(...)` per chiederlo all'utente), e stampa quanti film ha diretto come unico regista.
- Stampa la lista dei suoi film, separati da punto e virgola. Puoi usare il metodo [str.join](https://docs.python.org/3/library/stdtypes.html#str.join)
- Quanti film sono stati prodotti solo in Svizzera?
- Qual e' la durata media dei film prodotti solo in Svizzera?
[riprendi da quì]
- Elenca i loro titoli in una stringa, separati da un ritorno a capo.  Ne hai visto qualcuno?
- Elenca i registi dei film prodotti solo in Svizzera
- Sono usciti piu' film prima del 2000 o dopo il 2000? (Attenzione: usa la funzione `pd.to_numeric(...)` per convertire la colonna "year" in un tipo numerico.  Leggi bene la documentazione per capire come fare a gestire eventuali errori nel parsing delle stringhe).

In [4]:
print(f"Durata media:{df['duration'].mean()}")
print(f'{df["title"].loc[df["duration"].idxmax()]}')
print(f'{df["title"].loc[df["duration"].idxmin()]}')
print(f"{df.loc[df['year']==2001,'title'].sample()}")
regista="Quentin Tarantino"
print(len(df.loc[df["director"]==regista]))
print(";".join(df.loc[df["director"]==regista,"title"]))
print(len(df.loc[df["country"]=="Switzerland"]))
print(df.loc[df["country"]=="Switzerland","duration"].mean())
print("\n".join((df.loc[df["country"]=="Switzerland"])["title"]))
print("\n".join((df.loc[df["country"]=="Switzerland"])["director"]))
pred= pd.to_numeric(df["year"], "coerce") < 2000
cnt=0
for e in pred:
    if e == True:
        cnt+=1
suc= pd.to_numeric(df["year"], "coerce") > 2000
cnt2=0
for e in suc:
    if e:
        cnt2+=1
print(f"{cnt} : {cnt2}")

Durata media:100.35141808863781
La flor
Dragon Ball Z: La vendetta divina
36622    Lip Service
Name: title, dtype: object
12
Le iene;Pulp Fiction;Jackie Brown;Kill Bill - Volume 1;My Best Friend's Birthday;Bastardi senza gloria;Kill Bill - Volume 2;Grindhouse - A prova di morte;Django Unchained;The Hateful Eight;Kill Bill: The Whole Bloody Affair;C'era una volta a... Hollywood
87
94.66666666666667
Wachtmeister Studer
L'ultima speranza
Quattro in una jeep
Heidi
Uli, der Knecht
Heidi torna a casa
Uli, der Pächter
Bäckerei Zürrer
Charles mort ou vif
The Devil in Miss Jonas
Downtown - Die nackten Puppen der Unterwelt
Penitenziario femminile per reati sessuali
Frauen im Liebeslager
Mosquito der Schänder
Frenesie erotiche di una ninfomane
Porno shock
I fabbricasvizzeri
Folli piaceri delle porno prigioniere
Die Nichten der Frau Oberst
Sechs Schwedinnen von der Tankstelle
Il falò
Broken Silence
Katzendiebe
Nacht der Gaukler
Frauen für Zellenblock 9
Exklusiv
Die Sklavinnen
Insaziabili notti di una ninfomane
Komiker
HD-Soldat Läppli
Heidi
Hinter den sieben Gleisen
Neutre
Utopia Blues
Stille Liebe
Ernstfall in Havanna
Dällebach Kari
Achtung, fertig, Charlie!
Cargo
Sternenberg
Hildes Reise
Strähl
The Ring Thing
Absolut
Grounding - Die letzten Tage der Swissair
Nachbeben
Jeune homme
Vitus
Mein Name ist Eugen
Handyman
Breakout
Die Herbstzeitlosen
Comme des voleurs (à l'est)
I Was a Swiss Banker
Der Freund
Un autre homme
Sennentuntschi
Coeur animal
Die Standesbeamtin
Giulias Verschwinden
Stationspiraten
Der Sandmann
Clara e il segreto degli orsi
Trapped
Chimères
Das Missen Massaker
Rosie
Pause
Até Ver a Luz
Der Goalie bin ig
Pronti, partenza, march!
Der Kreis
Unter der Haut
Amateur Teens
Nichts passiert
Chrieg
Una campana per Ursli
Non tutte le sciagure vengono dal cielo
Goliath
Contro l'ordine divino
Mr. Moll e la fabbrica di cioccolato
Der Läufer
Streaker
Mario
Dene wos guet geit
Cronofobia
Platzspitzbaby
Leopold Lindtberg
Leopold Lindtberg
Leopold Lindtberg, Elizabeth Montagu
Luigi Comencini
Franz Schnyder
Franz Schnyder
Franz Schnyder
Kurt Früh
Alain Tanner
Erwin C. Dietrich
Jesús Franco
Jesús Franco
Jesús Franco
Marijan Vajda
Jesús Franco
Jesús Franco
Rolf Lyssy
Erwin C. Dietrich
Erwin C. Dietrich
Erwin C. Dietrich
Fredi M. Murer
Wolfgang Panzer
Markus Imboden
Michael Steiner, Pascal Walder
Jesús Franco
Florian Froschmayer
Jesús Franco
Jesús Franco
Markus Imboden
Alfred Rasser
Markus Imboden
Kurt Früh
Xavier Ruiz
Stefan Haupt
Christoph Schaub
Sabine Boss
Kurt Früh
Mike Eschmann
Ivan Engler, Ralph Etter
Christoph Schaub
Christof Vorster
Manuel Flurin Hendry
Marc Schippert
Romed Wyder
Michael Steiner
Stina Werenfels
Christoph Schaub
Fredi M. Murer
Michael Steiner
Jürg Ebe
Mike Eschmann
Bettina Oberli
Lionel Baier
Thomas Imbach
Micha Lewinsky
Lionel Baier
Michael Steiner
Séverine Cornamusaz
Micha Lewinsky
Christoph Schaub
Mike Schaerer
Peter Luisi
Tobias Ineichen
Philippe Weibel
Olivier Beguin
Michael Steiner
Marcel Gisler
Mathieu Urfer
Basil da Cunha
Sabine Boss
Oliver Rihs
Stefan Haupt
Claudia Lorenz
Niklaus Hilber
Micha Lewinsky
Simon Jaquemet
Xavier Koller
Michael Steiner
Dominik Locher
Petra Biondina Volpe
Manuel Flurin Hendry
Hannes Baumgartner
Peter Luisi
Marcel Gisler
Cyril Schäublin
Francesco Rizzi
Pierre Monnard
38717 : 45792

## Esercizio 2
- Chiedi all'utente di inserire una parola.  Per ogni film in cui il titolo o la descrizione contiene quella parola, visualizza titolo e descrizione per intero.
- Elenca le 100 parole piu' comuni all'interno dei titoli dei film.  Probabilmente avra' senso limitarti alle parole piu' lunghe di un certo numero di caratteri.
- Decidi un genere (ad esempio Horror).  Analizza le descrizioni dei film e stampa le parole che ricorrono piu' di frequente.

In [5]:
parola="odio"
print(df[df["title"].str.contains(parola)].loc[:,["title","description"]])
print(pd.Series(filter(lambda e:len(e)>3," ".join(df.title).split())).sort_values().value_counts()[:100])
print(df.loc[df["genre"]=="Horror","description"].str.split().explode().sort_values().value_counts())

                                                title  \
948                                     Debito d'odio
3690                              I pascoli dell'odio
6298                       Rosanna (l'odio e l'amore)
6447                           Le frontiere dell'odio
6570                              Più forte dell'odio
6908                        L'odio colpisce due volte
6914                            La Dinastia dell'odio
7386                   Vittime dell'odio e dell'amore
9128                             Il marchio dell'odio
9832                             Le colline dell'odio
10743                         L'odio esplode a Dallas
11228                             La scuola dell'odio
11282                            Con odio e con amore
13018             Mantieni l'odio per la tua vendetta
13200                                   Odio per odio
14721                       I lunghi giorni dell'odio
14813    Quei dannati giorni dell'odio e dell'inferno
15420                                  Spirale d'odio
16353                   McKlusky, metà uomo metà odio
17290                               Il seme dell'odio
17431             Mantieni l'odio per la tua vendetta
22624                              Io odio gli attori
24078       Mississippi Burning - Le radici dell'odio
24287                                  Il grande odio
24350                            Gli angeli dell'odio
28529                                Fra odio e amore
28966                                          L'odio
28981                          L'università dell'odio
30216               La linea sottile tra odio e amore
30561                                L'urlo dell'odio
31387    Star Wars: Episodio I - La minaccia fantasma
31430    Star Wars: Episodio II - L'attacco dei cloni
31431  Star Wars: Episodio III - La vendetta dei Sith
33065                          10 cose che odio di te
40030                         Amore e odio a New York
46581                Harsh Times - I giorni dell'odio
47332                       Ti odio, ti lascio, ti...
47814                                     El custodio
55752                         Indovina perché ti odio
59543                  Ballata dell'odio e dell'amore
72286                               L'odio che uccide

                                             description
948    Mary Turner goes up for three years on a crime...
3690   In 1854, Jeb Stuart, George Custer and other g...
6298   The saga of the Hatfield-and-McCoy feud is rom...
6447   Johnny Carter, performing sharpshooter, is ask...
6570   An Australian sheepman comes to Montana lookin...
6908   Sent to a dude ranch in the west to recover he...
6914   Set in 17th century Scotland, a young woman fa...
7386   During World War II, German soldiers occupy th...
9128   Sheriff Halliday doesn't approve of his childr...
9832   In 1941, Greek resistance entrusts an American...
10743  A man in a gleaming white suit comes to a smal...
11228  A black prison psychiatrist is assigned the di...
11282  A boy and a girl from two rival Gypsy families...
13018  A noble swordsman, whose arm had been chopped ...
13200  A self-loathing bank robber forms an uneasy al...
14721  A bounty, Benson is hunting down a vicious out...
14813  During the German invasion of Crete, a unit of...
15420  At an exclusive boys' school, a new gym teache...
16353  An ex con teams up with federal agents to help...
17290  A black anti-Apartheid activist and a British ...
17431  The martial world is now awash in one-armed kn...
22624  Hollywood in the 1940s. A tyrannical producer,...
24078  Two F.B.I. Agents with wildly different styles...
24287  A modernized version of the story which inspir...
24350  In the nuclear ravaged wasteland of Earth 2087...
28529  Hazel is a Protestant and Malachy a Catholic. ...
28966  24 hours in the lives of three young men in th...
28981  People from all different walks of life, encou...
30216  An observable, fast-talking party man Darnell ...
30561  An intellectual billionaire and two other men ...
31387  Two Jedi escape a hostile blockade to find all...
31430  Ten years after initially meeting, Anakin Skyw...
31431  Three years into the Clone Wars, the Jedi resc...
33065  A pretty, popular teenager can't go out on a d...
40030  Set in present day New York City, "Happy Hour"...
46581  A tough-minded drama about two friends in Sout...
47332  In a bid to keep their luxurious condo from th...
47814  A bodyguard of a top politician is so dedicate...
55752  While in his teens, Donny fathered a son, Todd...
59543  A young trapeze artist must decide between her...
72286  A bullied teenager is sent to a reform school ...
della       1015
Love         511
notte        317
Night        313
delle        305
            ...
uomini        87
Game          86
leggenda      86
Wild          85
Summer        85
Length: 100, dtype: int64
a              3176
the            2848
of             1947
to             1929
and            1405
               ...
bridge            1
brief             1
broadcast.        1
broadcaster       1
Öznur             1
Name: description, Length: 12147, dtype: int64

## Esercizio 3
- Crea una lista che contenga tutti i possibili generi di film (colonna `genre`).
- Per ogni genere `G`, aggiungi una colonna booleana `is_G` che contenga `True` solo se il film e' (anche) di quel genere.  Ad esempio un film con genre `Action,Horror` dovra' avere `is_Action = True`, `is_Horror = True`, ma `is_Animation = False`.
- Qual e' il genere associato a una durata maggiore?
- Per ogni decade a partire dal 1940, riporta il genere piu' comune.
- Ripeti l'analisi negli ultimi due punti, limitandoti ai film popolari.  Ragiona sulle colonne che abbiamo a disposizione: quale potrebbe essere un criterio per definire quando un film e' popolare?

In [6]:
mylist=list(df["genre"].unique())
tmpList=list()

for x in mylist:
    y=x.split(",")
    for z in y:
        tmpList.append(z)
newColumns=dict();

for g in mylist:
    col="is"+g
    newColumns[col]=df["genre"].str.split()==g

KeyboardInterrupt:

In [61]:

print(df.loc[:,["genre","duration"]].resample().sum().max())
(df.loc[pd.to_numeric(df["year"],"coerce")>1940,["year","genre"]].groupby(["year"]).max()).value_counts()

genre    WesternComedy, DramaAction, AdventureAdventure...
dtype: object

genre
Western                      60
War                           6
Drama, Romance                5
Thriller                      5
Drama                         4
Romance                       4
Western, Adventure            4
Drama, War                    3
War, Drama                    3
Western, Comedy               3
Comedy                        3
Western, Drama                3
Horror                        3
Drama, Musical, Romance       2
Drama, Thriller               2
Thriller, Western             1
Thriller, War                 1
Thriller, Horror              1
Action, Adventure             1
Western, Action               1
Western, Action, Drama        1
Western, Family               1
Thriller, Drama               1
Horror, Thriller              1
Sport                         1
Romance, Thriller             1
Musical                       1
Action, Adventure, Comedy     1
Horror, Mystery               1
Drama, Romance, War           1
Drama, History, Romance       1
Crime, Drama, Thriller        1
Comedy, Romance               1
Comedy, Musical, Romance      1
Comedy, Drama, War            1
Comedy, Drama                 1
Action, Drama                 1
Action, Crime, Fantasy        1
Western, Horror               1
dtype: int64

### Esercizio 4
Vorremmo utilizzare un tipo piu' corretto per la colonna `date_published`. Scopri come fare leggendo la [documentazione della funzione `pd.to_datetime`](https://pandas.pydata.org/docs/reference/api/pandas.to_datetime.html).  

Sovrascrivi la colonna `date_published` con il valore convertito in datetime.  Se dovessero esserci delle righe per cui non riusciamo a parsare la data, impostiamola a un valore nullo.

In [ ]:
pd.to_datetime(df["date_published"], errors='coerce')